version: '3'
services:
  db:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      MONGO_INITDB_DATABASE: yt_videos
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/python-docker
    depends_on:
      - db
